#!/bin/bash
#
# WRD Server Headless Installation Script
#
# This script installs and configures WRD Server for headless deployment
# with multi-user support, systemd integration, and resource isolation.
#
# Usage:
#   sudo ./install-headless.sh
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
WRD_USER="wrd-server"
WRD_GROUP="wrd-server"
WRD_HOME="/var/lib/wrd-server"
WRD_CONFIG_DIR="/etc/wrd-server"
WRD_LOG_DIR="/var/log/wrd-server"
WRD_RUN_DIR="/run/wrd-server"
BINARY_PATH="/usr/local/bin/wrd-server"

echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  WRD Server Headless Installation${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo ""

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root${NC}"
   exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    VERSION=$VERSION_ID
else
    echo -e "${RED}Error: Cannot detect OS${NC}"
    exit 1
fi

echo -e "${YELLOW}Detected OS: $OS $VERSION${NC}"
echo ""

# Install system dependencies
echo -e "${GREEN}[1/10] Installing system dependencies...${NC}"

case $OS in
    ubuntu|debian)
        apt-get update
        apt-get install -y \
            pipewire \
            libpipewire-0.3-dev \
            xdg-desktop-portal \
            libpam0g-dev \
            libsystemd-dev \
            build-essential \
            pkg-config \
            libssl-dev \
            cgroup-tools \
            systemd-container
        ;;
    fedora|rhel|centos)
        dnf install -y \
            pipewire \
            pipewire-devel \
            xdg-desktop-portal \
            pam-devel \
            systemd-devel \
            gcc \
            pkg-config \
            openssl-devel \
            libcgroup-tools
        ;;
    arch)
        pacman -S --noconfirm \
            pipewire \
            xdg-desktop-portal \
            pam \
            systemd \
            base-devel \
            openssl
        ;;
    *)
        echo -e "${YELLOW}Warning: Unknown OS, skipping package installation${NC}"
        ;;
esac

echo -e "${GREEN}✓ Dependencies installed${NC}"
echo ""

# Create system user and group
echo -e "${GREEN}[2/10] Creating system user and group...${NC}"

if ! getent group $WRD_GROUP > /dev/null 2>&1; then
    groupadd --system $WRD_GROUP
    echo -e "${GREEN}✓ Created group: $WRD_GROUP${NC}"
else
    echo -e "${YELLOW}Group $WRD_GROUP already exists${NC}"
fi

if ! getent passwd $WRD_USER > /dev/null 2>&1; then
    useradd --system \
        --home-dir $WRD_HOME \
        --shell /bin/false \
        --gid $WRD_GROUP \
        --groups video,render,input \
        --create-home \
        $WRD_USER
    echo -e "${GREEN}✓ Created user: $WRD_USER${NC}"
else
    echo -e "${YELLOW}User $WRD_USER already exists${NC}"
fi

echo ""

# Create directory structure
echo -e "${GREEN}[3/10] Creating directory structure...${NC}"

mkdir -p $WRD_CONFIG_DIR
mkdir -p $WRD_LOG_DIR
mkdir -p $WRD_RUN_DIR
mkdir -p $WRD_HOME/sessions
mkdir -p $WRD_HOME/recordings

chown -R $WRD_USER:$WRD_GROUP $WRD_HOME
chown -R $WRD_USER:$WRD_GROUP $WRD_LOG_DIR
chown -R $WRD_USER:$WRD_GROUP $WRD_RUN_DIR
chmod 750 $WRD_CONFIG_DIR
chmod 750 $WRD_LOG_DIR
chmod 750 $WRD_HOME

echo -e "${GREEN}✓ Directories created${NC}"
echo ""

# Copy binary
echo -e "${GREEN}[4/10] Installing WRD Server binary...${NC}"

if [ ! -f "target/release/wrd-server" ]; then
    echo -e "${RED}Error: Binary not found. Please run 'cargo build --release' first${NC}"
    exit 1
fi

cp target/release/wrd-server $BINARY_PATH
chmod 755 $BINARY_PATH
chown root:root $BINARY_PATH

echo -e "${GREEN}✓ Binary installed to $BINARY_PATH${NC}"
echo ""

# Generate default configuration
echo -e "${GREEN}[5/10] Generating default configuration...${NC}"

cat > $WRD_CONFIG_DIR/headless.toml << 'EOF'
# WRD Server Headless Configuration
# Auto-generated by install-headless.sh

listen_address = "0.0.0.0:3389"
enabled = true

[compositor]
compositor_type = "smithay"
default_resolution = [1920, 1080]
refresh_rate = 60
render_backend = "llvmpipe"
software_fallback = true
enable_dmabuf = true
memory_limit = 512

[multiuser]
enabled = true
max_sessions = 10
max_sessions_per_user = 2
port_allocation = "sequential"
base_port = 3389
port_range = 100
enable_persistence = true
persistence_dir = "/var/lib/wrd-server/sessions"
idle_timeout = 3600
enable_reconnection = true
reconnection_timeout = 300

[authentication]
provider = "pam"
pam_service = "wrd-server"
enable_password = true
enable_pubkey = false
enable_2fa = false
enable_cache = true
cache_timeout = 300
max_failed_attempts = 5
lockout_duration = 900

[resources]
enable_cgroups = true
cgroup_version = 2
cgroup_base = "wrd-server"
enable_oom_protection = true
oom_score_adj = -100
cpu_priority = 0
io_priority = "best-effort"

[resources.session_limits]
max_memory = 2048
max_swap = 0
cpu_shares = 1024
cpu_quota = 200
max_processes = 256
max_files = 4096
max_disk = 10240
max_bandwidth = 0

[resources.system_limits]
total_memory = 16384
total_cpu = 800
reserved_memory = 2048
reserved_cpu = 100

[portal]
backend_type = "embedded"
auto_grant_permissions = true
enable_emulation = true
dbus_connection = "session"
timeout = 30

[portal.permission_policy]
default_policy = "allow"
screencast_policy = "allow"
remote_desktop_policy = "allow"
clipboard_policy = "allow"

[autostart]
enabled = false
startup_delay = 1000

[session]
use_systemd_logind = true
session_class = "user"
session_type = "wayland"
enable_logging = true
log_dir = "/var/log/wrd-server"
enable_recording = false
cleanup_on_logout = true
kill_user_processes = false
EOF

chown root:$WRD_GROUP $WRD_CONFIG_DIR/headless.toml
chmod 640 $WRD_CONFIG_DIR/headless.toml

echo -e "${GREEN}✓ Configuration file created${NC}"
echo ""

# Create PAM configuration
echo -e "${GREEN}[6/10] Creating PAM configuration...${NC}"

cat > /etc/pam.d/wrd-server << 'EOF'
# WRD Server PAM configuration
auth       required     pam_env.so
auth       required     pam_unix.so
account    required     pam_unix.so
session    required     pam_unix.so
session    required     pam_limits.so
EOF

echo -e "${GREEN}✓ PAM configuration created${NC}"
echo ""

# Install systemd service files
echo -e "${GREEN}[7/10] Installing systemd service files...${NC}"

cp deploy/systemd/wrd-server-headless.service /etc/systemd/system/
cp deploy/systemd/wrd-server-headless@.service /etc/systemd/system/

systemctl daemon-reload

echo -e "${GREEN}✓ Systemd service files installed${NC}"
echo ""

# Configure cgroups v2
echo -e "${GREEN}[8/10] Configuring cgroups v2...${NC}"

# Check if cgroups v2 is available
if [ -f /sys/fs/cgroup/cgroup.controllers ]; then
    echo -e "${GREEN}✓ cgroups v2 detected${NC}"

    # Enable delegation for systemd service
    mkdir -p /etc/systemd/system/wrd-server-headless.service.d
    cat > /etc/systemd/system/wrd-server-headless.service.d/delegate.conf << 'EOF'
[Service]
Delegate=yes
DelegateSubgroup=wrd-sessions
EOF

    systemctl daemon-reload
    echo -e "${GREEN}✓ cgroups delegation configured${NC}"
else
    echo -e "${YELLOW}Warning: cgroups v2 not available, resource limits will not work${NC}"
fi

echo ""

# Configure firewall
echo -e "${GREEN}[9/10] Configuring firewall...${NC}"

if command -v ufw &> /dev/null; then
    ufw allow 3389/tcp comment "WRD Server RDP"
    ufw allow 3389:3489/tcp comment "WRD Server user sessions"
    echo -e "${GREEN}✓ UFW rules added${NC}"
elif command -v firewall-cmd &> /dev/null; then
    firewall-cmd --permanent --add-port=3389/tcp
    firewall-cmd --permanent --add-port=3389-3489/tcp
    firewall-cmd --reload
    echo -e "${GREEN}✓ Firewalld rules added${NC}"
else
    echo -e "${YELLOW}Warning: No firewall detected, please configure manually${NC}"
fi

echo ""

# Enable and start service
echo -e "${GREEN}[10/10] Enabling service...${NC}"

systemctl enable wrd-server-headless.service

echo -e "${GREEN}✓ Service enabled${NC}"
echo ""

# Print summary
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Installation Complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo ""
echo "Service management:"
echo "  Start:   systemctl start wrd-server-headless"
echo "  Stop:    systemctl stop wrd-server-headless"
echo "  Status:  systemctl status wrd-server-headless"
echo "  Logs:    journalctl -u wrd-server-headless -f"
echo ""
echo "Configuration:"
echo "  Config:  $WRD_CONFIG_DIR/headless.toml"
echo "  Logs:    $WRD_LOG_DIR/"
echo "  Data:    $WRD_HOME/"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Review and customize $WRD_CONFIG_DIR/headless.toml"
echo "2. Generate TLS certificates (or configure Let's Encrypt)"
echo "3. Start the service: systemctl start wrd-server-headless"
echo "4. Check status: systemctl status wrd-server-headless"
echo "5. Connect with RDP client to: <server-ip>:3389"
echo ""
echo -e "${GREEN}Happy headless RDP streaming!${NC}"
